version: "3"
services:
    redis:
        image: bitnami/redis:4.0
        container_name: redis
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_AOF_ENABLED=no
        ports:
            - 6379:6379
    php73:
        build:
            context: .
            dockerfile: Dockerfile.php73
        image: php73:1.0.0
        container_name: php73
        ports: 
            - 80:80
        volumes:
            - php73-data:/var/www/html
    nodejs10:
        build:
            context: .
            dockerfile: Dockerfile.nodejs
        image: nodejs:1.0.0
        container_name: nodejs10
        volumes:
            - nodejs-data:/app
    nodejs14:
        build:
            context: .
            dockerfile: Dockerfile.nodejs14
        image: nodejs:1.0.0
        container_name: nodejs14
        volumes:
            - nodejs-data:/app
    golang:
        build:
            context: .
            dockerfile: Dockerfile.golang
        image: golang:1.0.0
        container_name: golang
        volumes: 
            - golang-data:/app
    dotnet:
        build:
            context: .
            dockerfile: Dockerfile.dotnet
        image: dotnet:1.0.0
        container_name: dotnet
        volumes:
            - dotnet-data:/app
    mongodb:
        image: bitnami/mongodb:4.4
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - mongodb-data:/bitnami/mongodb 

volumes:
    php73-data:
    nodejs-data:
    golang-data:
    dotnet-data:
    mongodb-data: