version: "3"
services:
    redis:
        image: bitnami/redis:4.0
        container_name: redis
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_AOF_ENABLED=no
        ports:
            - 6379:6379
    php73:
        build:
            context: .
            dockerfile: Dockerfile.php73
        image: php73:1.0.0
        container_name: php73
        volumes:
            - php_data:/var/www/html
    php70:
        build:
            context: .
            dockerfile: Dockerfile.php70
        image: php70:1.0.0
        container_name: php70
        volumes:
            - php_data:/var/www/html
        ports:
            - 9000:80
    nodejs10:
        build:
            context: .
            dockerfile: Dockerfile.nodejs
        image: nodejs:1.0.0
        container_name: nodejs10
        volumes:
            - nodejs_data:/app
    nodejs-latest:
        build:
            context: .
            dockerfile: Dockerfile.nodejs-latest
        image: nodejs:1.0.0
        container_name: nodejs-latest
        volumes:
            - nodejs_data:/app
    golang:
        build:
            context: .
            dockerfile: Dockerfile.golang
        image: golang:1.0.0
        container_name: golang
        security_opt:
            - seccomp:unconfined
        volumes: 
            - golang_data:/app
    ruby:
        build:
            context: .
            dockerfile: Dockerfile.ruby
        image: ruby:1.0.0
        container_name: ruby
        volumes: 
            - ruby_data:/app
    dotnet:
        build:
            context: .
            dockerfile: Dockerfile.dotnet
        image: dotnet:1.0.0
        container_name: dotnet
        volumes:
            - dotnet_data:/app
    mongodb:
        image: bitnami/mongodb:5.0
        container_name: mongodb
        environment:
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_ADVERTISED_HOSTNAME=mongodb
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/bitnami/mongodb
    deskdev:
        build:
            context: .
            dockerfile: Dockerfile.deskdev
        image: deskdev:1.0.0
        container_name: deskdev
        environment:
            - DISPLAY=:0
            - WAYLAND_DISPLAY=:0
            - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
            - PULSE_SERVER=/mnt/wslg/PulseServer
        volumes:
            - golang_data:/app
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /mnt/wslg:/mnt/wslg

volumes:
    php_data:
    nodejs_data:
    golang_data:
    ruby_data:
    dotnet_data:
    mongodb_data: